#pragma once

#include <cstdint>

namespace m3 {

struct Rgb {
  float r, g, b;
};

// All 53 colour roles generated by material_color_utilities from a single
// source colour. Ordered by palette family.
enum class ColorRole : uint8_t {
  // — Primary palette —
  Primary,                // Main brand accent. Filled button bg, active states.
  OnPrimary,              // Content (text, icons) ON primary-coloured areas.
  PrimaryContainer,       // Container variant. Tonal buttons, selected chips.
  OnPrimaryContainer,     // Content ON primary-container.
  PrimaryFixed,           // Light-mode fixed primary (no dark-mode shift).
  PrimaryFixedDim,        // Dimmer version of primary-fixed.
  OnPrimaryFixed,         // Content on primary-fixed.
  OnPrimaryFixedVariant,  // Variant content on primary-fixed.

  // — Secondary palette —
  Secondary,              // Secondary brand accent.
  OnSecondary,            // Content ON secondary.
  SecondaryContainer,     // Container variant.
  OnSecondaryContainer,   // Content ON secondary-container.
  SecondaryFixed,
  SecondaryFixedDim,
  OnSecondaryFixed,
  OnSecondaryFixedVariant,

  // — Tertiary palette —
  Tertiary,               // Tertiary brand accent. Progress, input focus.
  OnTertiary,
  TertiaryContainer,
  OnTertiaryContainer,
  TertiaryFixed,
  TertiaryFixedDim,
  OnTertiaryFixed,
  OnTertiaryFixedVariant,

  // — Error palette —
  Error,                  // Destructive colour.
  OnError,                // Content ON error.
  ErrorContainer,         // Container variant.
  OnErrorContainer,

  // — Surface palette (light → dark gradient) —
  Surface,                // Default page / app background.
  OnSurface,              // Primary text content.
  SurfaceVariant,         // Slightly shifted surface for cards, menus.
  OnSurfaceVariant,       // Secondary text, captions.

  // Surface tonal variants (M3 Expressive 2025):
  SurfaceDim,             // Darkest surface family member.
  SurfaceBright,          // Lightest surface family member.
  SurfaceContainerLowest, // Below-surface container (drawer bg).
  SurfaceContainerLow,    // Low container (search bar bg).
  SurfaceContainer,       // Default container (nav bar, bottom sheet bg).
  SurfaceContainerHigh,   // High container (dialog bg).
  SurfaceContainerHighest,// Highest container (menu, popup bg).

  // — Inverse palette —
  InverseSurface,         // Inverted surface (snackbar, tooltip bg).
  InverseOnSurface,       // Content on inverse-surface.
  InversePrimary,         // Primary for UI on surface (snackbar button).

  // — Other —
  Outline,                // Strong borders, dividers (moderate emphasis).
  OutlineVariant,         // Low-emphasis borders (disabled, subtle dividers).
  Shadow,                 // Shadow colour for elevation.
  Scrim,                  // Scrim / overlay dim background.
  SurfaceTint,            // Overlay tint for elevation colour shift.
};

// A colour specification can reference a semantic role OR provide a fixed RGB
// + optional alpha override.
struct ColorSpec {
  ColorRole role;          // semantic role
  uint8_t alpha = 255;     // 0–255 opacity override (255 = use role's full)
  bool fixed = false;      // true = use fixedR/G/B instead of role
  float fixedR = 0.0f;
  float fixedG = 0.0f;
  float fixedB = 0.0f;
};

} // namespace m3
